version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres_for_mail
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_dev
      POSTGRES_PASSWORD: passwordForPostgres